publish: make more robust with plumbing commands
Using git-checkout had the disadvantage that it would delete the
committed files.  Instead, use git-symbolic-ref to manually change
branches, after first verifying that the work tree and index are clean.
Then, delete the index and add the files as before.  However, only
commit if there is a change.  Finally, switch back using
git-symbolic-ref.

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -3,9 +3,26 @@ if [ $# -eq 0 ]; then
     echo "USAGE: $0 <files>" >&2
     exit 1
 fi
+if ! git diff --quiet; then
+    echo >&2
+    echo "ERROR: working tree is dirty; aborting..." >&2
+    echo >&2
+    exit 2
+fi
+if ! git diff --quiet --cached; then
+    echo >&2
+    echo "ERROR: index is dirty; aborting..." >&2
+    echo >&2
+    exit 2
+fi
+HEAD=`git symbolic-ref HEAD`
 SHA=`git rev-parse HEAD`
-git checkout gh-pages && \
-rm -f .git/index && \
-git add "$@" && \
-git commit -m "build from $SHA" && \
-git checkout -
+git symbolic-ref HEAD refs/heads/gh-pages || exit $?
+rm -f .git/index || exit $?
+git add "$@" || exit $?
+if git diff --quiet --cached; then
+    echo "nothing to commit..."
+else
+    git commit -m "build from $SHA" || exit $?
+fi
+git symbolic-ref HEAD "$HEAD" || exit $?
